[package]
name = "tea_strategy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
pl = ["tevec/pl", "time"]
ndarray = ["tevec/ndarray"]
time = ["tevec/time"]

[dependencies]
itertools = "0.13"
smartstring = "1.0"
derive_more = { version = "0.99", features = ["from"] }
serde = { version = "1.0", features = ["derive"] }

[dependencies.tevec]
git = "https://github.com/Teamon9161/tevec.git"
branch = "master"
default-features = false
features = ["agg", "rolling", "map", "time"]
