[package]
name = "tea_strategy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []


[dependencies]
itertools = "0.12.1"
serde = { version = "1.0", features = ["derive"] }

[dependencies.tea-core]
git = "https://github.com/Teamon9161/tevec.git"
rev = "33c2f7e"
default-features = false
features = []


[dependencies.tea-rolling]
git = "https://github.com/Teamon9161/tevec.git"
rev = "33c2f7e"